apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: github-api-server
  namespace: skygear-lambda-check
  annotations:
    ingress.kubernetes.io/whitelist-source-range: 192.30.252.0/22
spec:
  rules:
  - host: skygear-lambda-check.pandawork.com
    http:
      paths:
      - path: /
        backend:
          serviceName: github-api-server
          servicePort: 80
